### ISSUE TITLE
More complete request url validation at compile time

### ISSUE THREAD

**Issue by LeonardTibben** [Baseflow/stellar-rust-sdk#8]
Currently every request has a `validate` function which checks the query parameters of a request. Right now not every query parameter of every request is validated.

**Comment by ejorritsma** [comment]
Encountered validation TODOs:
* In `single_claimable_balance_request`: // TODO: Validate claimable_balance_id
* In `all_assets_request`:   
     - // TODO: implement full asset code regex
     - // TODO: implement full asset issuer regex

Many forms of validation seem to be duplicated across routes, such as the validation of cursor/limit/order. 
Maybe we could make a collection of validators of some sort? :)

**Comment by ejorritsma** [comment]
Comments moved here from https://github.com/Baseflow/stellar-rust-sdk/pull/12
by Thomas:

***

[src/assets/all_assets_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-f98bf166c89c26b45b9af0a9b7e8a28c7c8ba78d7d3a31c1eabfb90244952969)
Comment on lines +77 to +79
        if asset_code.len() > 12 {
            return Err("asset_code must be 12 characters or less".to_string());
        }
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404227169)

These are still runtime errors. We could introduce an 'InvalidAssetRequest' state and return this if the asset_code > 12.


***


[src/assets/all_assets_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-f98bf166c89c26b45b9af0a9b7e8a28c7c8ba78d7d3a31c1eabfb90244952969)
Comment on lines +94 to +96
        if asset_issuer.len() != 56 {
            return Err("asset_issuer must be 56 characters".to_string());
        }
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404230152)

These are still runtime errors. We could introduce an 'InvalidAssetRequest' state and return this if the asset_issuer > 12.


***

[src/assets/all_assets_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-f98bf166c89c26b45b9af0a9b7e8a28c7c8ba78d7d3a31c1eabfb90244952969)
        self
    pub fn set_cursor(self, cursor: u32) -> Result<AllAssetsRequest, String> {
        if cursor < 1 {
            return Err("cursor must be greater than or equal to 1".to_string());
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404234497)

These are still runtime errors. We could introduce an 'InvalidAssetRequest' state and return this if the cursor < 1.
By the way, what happens if this is 0? Is this really an invalid use case? The docs do not describe a limitation for this.

***

[src/assets/all_assets_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-f98bf166c89c26b45b9af0a9b7e8a28c7c8ba78d7d3a31c1eabfb90244952969)
    pub fn set_limit(&mut self, limit: u32) -> &mut Self {
        self.limit = Some(limit);
        self
    pub fn set_limit(self, limit: u32) -> Result<AllAssetsRequest, String> {
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404235243)

We should set the limit type to u8, which only allows a maximum of 255. This is still out of bounds, but at least I cannot add a large value like 10.000. This narrows down the fail rate.

***

[src/assets/all_assets_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-f98bf166c89c26b45b9af0a9b7e8a28c7c8ba78d7d3a31c1eabfb90244952969)
Comment on lines +128 to +130
        if limit < 1 || limit > 200 {
            return Err("limit must be between 1 and 200".to_string());
        }
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404236690)

These are still runtime errors. We could introduce an 'InvalidAssetRequest' state and return this if the limit < 1 or > 200.

***

[src/claimable_balances/all_claimable_balances_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-8d572f886df13907044f0e5f3f0605d18d2107d053c439c9f8609e336c72ab92)
Comment on lines 30 to +32
}

impl Request for AllClaimableBalancesRequest {

impl AllClaimableBalancesRequest {
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404242993)

A lot of the comments from the all assets request also apply here. There should be an InvalidClaimableBalancesRequest state, which does not allow for an empty request without any parameters. Check the type for limit, to trim it down to the smallest possible value that matches the limits of the request.

***

[src/ledgers/ledgers_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-6f5476ef41b90a2c9b6f1f7cc303ed05183eb7227ed5ea976af7300acf575496)
Comment on lines +62 to +64
        if cursor < 1 {
            return Err("cursor must be greater than or equal to 1".to_string());
        }
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404258500)

The same remarks as earlier. These are still runtime exceptions, but could return an InvalidLedgerRequest state.

***

[src/ledgers/ledgers_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-6f5476ef41b90a2c9b6f1f7cc303ed05183eb7227ed5ea976af7300acf575496)
Comment on lines +81 to +84
    pub fn set_limit(self, limit: u32) -> Result<LedgersRequest, String> {
        if limit < 1 || limit > 200 {
            return Err("limit must be between 1 and 200".to_string());
        }
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404258864)

The same remarks as ealier. These are still runtime exceptions, but could return an InvalidLedgerRequest state.
Also, let's size limit down to a u8.

***

[src/ledgers/single_ledger_request.rs](https://github.com/Baseflow/stellar-rust-sdk/pull/12/files/6870fe0d1ef803e342352c0b0493a03d829a725c#diff-9bd373b15418cfefb0379076f464783ac785b3fc6f45e5da2acd3462be70e938)
Comment on lines +32 to +34
        if sequence < 1 {
            return Err("sequence must be greater than or equal to 1".to_string());
        }
Member
@[tluijken](https://github.com/tluijken) tluijken [Nov 24, 2023](https://github.com/Baseflow/stellar-rust-sdk/pull/12#discussion_r1404268070)

Same as before. We should implement this for a NoSequence variant and return a Sequence variant. We can set this only once. Try to remedy this runtime error with an InvalidSequence state.

**Comment by ejorritsma** [comment]
In `AccountsRequest`: check that we do not have an asset filter with the `AssetType::Native` variant.

Then we'd get the following response:
However this does not match how the API works (anymore?). When sending a request with the 'Native' asset filter, we get the following response:
```json
{
  "type": "https://stellar.org/horizon-errors/bad_request",
  "title": "Bad Request",
  "status": 400,
  "detail": "The request you sent was invalid in some way.",
  "extras": {
    "invalid_field": "asset",
    "reason": "you can't filter by asset: native"
  }
}
```
